### ISSUE TITLE
协议和谐了?

### ISSUE THREAD

**Issue by qwwqw716** [Undef1nedTeam/Gensh1n#7]
使用zone无法进服
![image](https://github.com/user-attachments/assets/4f8a0371-e73b-44ec-8c65-04e42efaa9ce)

**Comment by ImAlexBlock** [comment]
关掉zone提供的布吉岛协议再试试

**Comment by qwwqw716** [comment]
关不关都一样

**Comment by qwwqw716** [comment]
这就是关掉协议出现的情况

**Comment by ImAlexBlock** [comment]
尝试使用myth，作者应该是只再myth下测试过

**Comment by qwwqw716** [comment]
我没买myth😭
